# Generated by Django 5.2.12 on 2026-05-09 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'areas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Docentes',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('titulo_academico', models.TextField(blank=True, null=True)),
                ('especialidad', models.TextField(blank=True, null=True)),
                ('fecha_ingreso_institucion', models.DateField(blank=True, null=True)),
                ('anos_experiencia', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'docentes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tutores',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('apellido', models.TextField(blank=True, null=True)),
                ('ci', models.TextField(blank=True, null=True)),
                ('telefono', models.TextField(blank=True, null=True)),
                ('ocupacion', models.TextField(blank=True, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tutores',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('apellido', models.TextField()),
                ('email', models.TextField(unique=True)),
                ('password_hash', models.TextField()),
                ('ci', models.TextField(unique=True)),
                ('telefono', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DimensionesEvaluacion',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('puntaje_maximo', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('orden', models.IntegerField()),
                ('gestion', models.IntegerField()),
            ],
            options={
                'db_table': 'dimensiones_evaluacion',
                'managed': True,
                'unique_together': {('nombre', 'gestion')},
            },
        ),
        migrations.CreateModel(
            name='Grados',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nivel', models.TextField()),
                ('numero', models.IntegerField()),
                ('paralelo', models.CharField(max_length=1)),
                ('gestion', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'grados',
                'managed': True,
                'unique_together': {('nivel', 'numero', 'paralelo', 'gestion')},
            },
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('primer_apellido', models.TextField(unique=True)),
                ('segundo_apellido', models.TextField(blank=True, null=True)),
                ('nombres', models.TextField()),
                ('ci', models.TextField(blank=True, null=True, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=1, null=True)),
                ('estado', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.grados')),
                ('tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.tutores')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='core.usuarios')),
            ],
            options={
                'db_table': 'estudiantes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DocenteAsignacion',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.areas')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.docentes')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.grados')),
            ],
            options={
                'db_table': 'docente_asignacion',
                'managed': True,
                'unique_together': {('docente', 'grado', 'area')},
            },
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('indicador', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.docenteasignacion')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.estudiantes')),
            ],
            options={
                'db_table': 'notas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NotaDetalle',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('valor', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.dimensionesevaluacion')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.notas')),
            ],
            options={
                'db_table': 'nota_detalle',
                'managed': True,
                'unique_together': {('nota', 'dimension')},
            },
        ),
        migrations.CreateModel(
            name='Periodos',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('numero', models.IntegerField()),
                ('gestion', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'periodos',
                'managed': True,
                'unique_together': {('numero', 'gestion')},
            },
        ),
        migrations.AddField(
            model_name='notas',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.periodos'),
        ),
        migrations.CreateModel(
            name='Licencias',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('motivo', models.TextField(blank=True, null=True)),
                ('requiere_certificado', models.BooleanField(blank=True, null=True)),
                ('certificado_adjunto', models.TextField(blank=True, null=True)),
                ('aprobado', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.estudiantes')),
                ('aprobado_por', models.ForeignKey(blank=True, db_column='aprobado_por', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='licencias_aprobado_por_set', to='core.usuarios')),
                ('solicitado_por', models.ForeignKey(db_column='solicitado_por', on_delete=django.db.models.deletion.DO_NOTHING, to='core.usuarios')),
            ],
            options={
                'db_table': 'licencias',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='docentes',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='core.usuarios'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('valor_anterior', models.IntegerField(blank=True, null=True)),
                ('valor_nuevo', models.IntegerField(blank=True, null=True)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('fecha_cambio', models.DateTimeField(blank=True, null=True)),
                ('nota_detalle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.notadetalle')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.usuarios')),
            ],
            options={
                'db_table': 'audit_log',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('dia_semana', models.IntegerField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('aula', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.docenteasignacion')),
            ],
            options={
                'db_table': 'horarios',
                'managed': True,
                'unique_together': {('asignacion', 'dia_semana', 'hora_inicio')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='notas',
            unique_together={('estudiante', 'asignacion', 'periodo')},
        ),
        migrations.CreateModel(
            name='UsuarioRoles',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.roles')),
                ('asignado_por', models.ForeignKey(db_column='asignado_por', on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuarioroles_asignado_por_set', to='core.usuarios')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.usuarios')),
            ],
            options={
                'db_table': 'usuario_roles',
                'managed': True,
                'unique_together': {('usuario', 'rol')},
            },
        ),
        migrations.CreateModel(
            name='PeriodoEstados',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('cerrado', models.BooleanField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.grados')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.periodos')),
                ('cerrado_por', models.ForeignKey(blank=True, db_column='cerrado_por', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.usuarios')),
            ],
            options={
                'db_table': 'periodo_estados',
                'managed': True,
                'unique_together': {('grado', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='Asistencias',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('estado', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.estudiantes')),
                ('registrado_por', models.ForeignKey(db_column='registrado_por', on_delete=django.db.models.deletion.DO_NOTHING, to='core.usuarios')),
            ],
            options={
                'db_table': 'asistencias',
                'managed': True,
                'unique_together': {('estudiante', 'fecha')},
            },
        ),
    ]
