# Generated by Django 5.2.12 on 2026-05-13 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('puntaje_maximo', models.IntegerField(default=100)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.docenteasignacion')),
                ('dimension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.dimensionesevaluacion')),
            ],
            options={
                'db_table': 'actividades',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ActividadNotas',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('valor', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.actividades')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.estudiantes')),
            ],
            options={
                'db_table': 'actividad_notas',
                'managed': True,
                'unique_together': {('actividad', 'estudiante')},
            },
        ),
    ]
